### ISSUE TITLE
BUG - Achat

### ISSUE THREAD

**Issue by PabloDEV26** [Barwoz/bBarberShop#1]
Petit bug lors de l'achat pour la coupe du coiffeur, même si le joueur à 0 dollars sur lui la coupe fonctionne mais par contre après impossible d'ouvrir le menu 'coiffeur' ..
Il faut bloquer quand le joueur n'as pas de tunes, il ne peux pas avoir la coupe ( logique )

**Comment by Barwoz** [comment]
Bonjour, tu peux tester le bug est normalement réglé. Tiens moi au courant

**Comment by KeyRoDev57** [comment]
J'ai un soucis des que j'appuie sur E ca me freeze mon joueur

**Comment by Barwoz** [comment]
Et voila, désolé du bug !!! j'en ai profiter pour modifier deux trois truc en plus
